title: 123hp.com/setup | HP Printer DeskJet | Install HP DeskJet Printer
description: Go 123.hp.com/setup and get setup instructions, Printer software driver installation instructions and troubleshooting tips.
